site:
  id: default
  base_url: "http://127.0.0.1:8080/" # must end with /
  title: "Notepub â€” SEO-friendly websites from Markdown without CMS"
  description: "Create fast SEO-optimized websites and documentation from Markdown without CMS and dependencies"
  default_og_image: "/assets/notepub_og.png"
content:
  source: "local"
  local_dir: "./content/en"
paths:
  file_root: ./.notepub
  artifacts_dir: ./.notepub/artifacts
  snapshot_file: ./.notepub/snapshot/objects.json
  cache_root: ./.notepub/cache
theme:
  dir: "."
  name: "theme"
  templates_subdir: "templates"
  assets_subdir: "assets"
rules_path: "./rules.yaml"
server:
  listen: "127.0.0.1:8080"

robots:
  disallow:
    - "/private/"
  extra: |
    # Custom rules here

cache:
  html_ttl_seconds: 600
  stale_if_error_seconds: 604800
